version: '3.8'

services:
  redis:
    image: redis:7
    container_name: edibubble_redis
    ports:
      - "6379:6379"
    networks:
      - edibubble-net

  postgres:
    image: postgres:16
    container_name: edibubble_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superlongsecretpassword
      POSTGRES_DB: edibubble
    ports:
      - "5432:5432"
    networks:
      - edibubble-net
    volumes:
      - pg_data:/var/lib/postgresql/data

  migrate-up:
    image: migrate/migrate
    depends_on:
      - postgres
    networks:
      - edibubble-net
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://admin:superlongsecretpassword@postgres:5432/edibubble?sslmode=disable",
        "up"
      ]
  migrate-down:
    image: migrate/migrate
    depends_on:
      - postgres
    networks:
      - edibubble-net
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://admin:superlongsecretpassword@postgres:5432/edibubble?sslmode=disable",
        "down"
      ]


volumes:
  pg_data:

networks:
  edibubble-net:
    driver: bridge
