version: '3.8'

services:
  redis:
    image: redis:7
    container_name: auth_redis
    ports:
      - "6379:6379"
    networks:
      - auth-net

  postgres:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superlongsecretpassword
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    networks:
      - auth-net
    volumes:
      - pg_data:/var/lib/postgresql/data

  migrate-up:
    image: migrate/migrate
    depends_on:
      - postgres
    networks:
      - auth-net
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://admin:superlongsecretpassword@postgres:5432/auth?sslmode=disable",
        "up"
      ]
  migrate-down:
    image: migrate/migrate
    depends_on:
      - postgres
    networks:
      - auth-net
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://admin:superlongsecretpassword@postgres:5432/auth?sslmode=disable",
        "down",
        "-all"
      ]


volumes:
  pg_data:

networks:
  auth-net:
    driver: bridge
