// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*)
FROM audit_logs
WHERE $1::uuid IS NULL OR target_user_id = $1::uuid
`

func (q *Queries) CountAuditLogs(ctx context.Context, targetUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, targetUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM users
WHERE ($1::text IS NULL
         OR username ILIKE '%' || $1::text || '%'
         OR email ILIKE '%' || $1::text || '%')
  AND ($2::user_status IS NULL OR status = $2::user_status)
  AND ($3::user_role IS NULL OR role = $3::user_role)
`

type CountUsersParams struct {
	Search pgtype.Text
	Status NullUserStatus
	Role   NullUserRole
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Status, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
  actor_id, actor_username, target_user_id, target_username, target_email,
  action, reason, ip, user_agent
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9
)
`

type CreateAuditLogParams struct {
	ActorID        pgtype.UUID
	ActorUsername  pgtype.Text
	TargetUserID   pgtype.UUID
	TargetUsername pgtype.Text
	TargetEmail    pgtype.Text
	Action         AuditAction
	Reason         pgtype.Text
	Ip             pgtype.Text
	UserAgent      pgtype.Text
}

// Used by admin_service.go for actions the field-diff triggers in
// 002_log_triggers.up.sql don't (fully) cover on their own: force-logout
// and admin-initiated password resets touch no users-table column at all,
// and user_ban/user_unban/change_role/user_deleted here carry a specific,
// searchable action type plus a human-written reason and request
// ip/user_agent, none of which the generic 'update_user' trigger row
// captures. Both rows existing side by side for the same action is
// intentional, not duplication: the trigger row is a tamper-evident record
// of the literal column change that fires no matter what application code
// did or didn't do; this row is the human-readable "why".
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorID,
		arg.ActorUsername,
		arg.TargetUserID,
		arg.TargetUsername,
		arg.TargetEmail,
		arg.Action,
		arg.Reason,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const getUserByIDAdmin = `-- name: GetUserByIDAdmin :one
SELECT id, email, username, username_display, status, role, created_at,
       last_login, last_password_change, origin, deleted_at
FROM users
WHERE id = $1
`

type GetUserByIDAdminRow struct {
	ID                 pgtype.UUID
	Email              string
	Username           string
	UsernameDisplay    string
	Status             NullUserStatus
	Role               UserRole
	CreatedAt          pgtype.Timestamptz
	LastLogin          pgtype.Timestamptz
	LastPasswordChange pgtype.Timestamptz
	Origin             NullUserOrigin
	DeletedAt          pgtype.Timestamptz
}

// Unlike every other user lookup in this codebase, this deliberately does
// NOT filter out soft-deleted accounts — an admin looking up a user by ID
// (e.g. from an audit log entry) needs to find them either way.
func (q *Queries) GetUserByIDAdmin(ctx context.Context, id pgtype.UUID) (GetUserByIDAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDAdmin, id)
	var i GetUserByIDAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.UsernameDisplay,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.LastLogin,
		&i.LastPasswordChange,
		&i.Origin,
		&i.DeletedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, actor_username, actor_email, target_user_id,
       target_username, target_email, action, changes, reason, ip,
       user_agent, created_at
FROM audit_logs
WHERE $1::uuid IS NULL OR target_user_id = $1::uuid
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsParams struct {
	TargetUserID pgtype.UUID
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.TargetUserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorUsername,
			&i.ActorEmail,
			&i.TargetUserID,
			&i.TargetUsername,
			&i.TargetEmail,
			&i.Action,
			&i.Changes,
			&i.Reason,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, username_display, status, role, created_at,
       last_login, deleted_at
FROM users
WHERE ($1::text IS NULL
         OR username ILIKE '%' || $1::text || '%'
         OR email ILIKE '%' || $1::text || '%')
  AND ($2::user_status IS NULL OR status = $2::user_status)
  AND ($3::user_role IS NULL OR role = $3::user_role)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Search     pgtype.Text
	Status     NullUserStatus
	Role       NullUserRole
	PageOffset int32
	PageLimit  int32
}

type ListUsersRow struct {
	ID              pgtype.UUID
	Email           string
	Username        string
	UsernameDisplay string
	Status          NullUserStatus
	Role            UserRole
	CreatedAt       pgtype.Timestamptz
	LastLogin       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

// search matches username (canonical, lowercase) or email, case-insensitive
// substring. Any of search/status/role may be omitted (NULL) to not filter
// on that dimension.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Status,
		arg.Role,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.UsernameDisplay,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
			&i.LastLogin,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActorID = `-- name: SetActorID :exec

SELECT set_config('app.actor_id', $1::text, true)
`

// Queries backing the admin API surface (internal/services/admin_service.go).
// Every mutating query here is meant to be run through postgres.WithActor,
// which sets the transaction-local app.actor_id the audit-log triggers in
// 002_log_triggers.up.sql read — without it, admin-performed changes would
// still be logged, just with a NULL actor, indistinguishable from a user
// acting on their own account.
// Must run in the same transaction as the query it's attributing — it uses
// set_config's is_local=true, which is transaction-scoped, not
// session-scoped (a pooled connection is reused across unrelated requests,
// so a session-scoped setting would leak into the next one).
func (q *Queries) SetActorID(ctx context.Context, actorID string) error {
	_, err := q.db.Exec(ctx, setActorID, actorID)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users
SET role = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SetUserRoleParams struct {
	Role UserRole
	ID   pgtype.UUID
}

// trg_prevent_admin_demotion (003_prevent_triggers.up.sql) independently
// blocks this at the database level if the target is currently an admin
// and the new role isn't — a backstop against this application-level
// check ever having a bug, not a substitute for it.
func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.Role, arg.ID)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users
SET status = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SetUserStatusParams struct {
	Status NullUserStatus
	ID     pgtype.UUID
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.Status, arg.ID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}
