// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_identities.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailAuth = `-- name: CreateEmailAuth :exec
INSERT INTO auth_identities (user_id, provider, provider_user_id, password_hash)
VALUES (
  $1, 
  'email',
  lower($2),                    -- provider_user_id = normalized email
  $3
)
`

type CreateEmailAuthParams struct {
	UserID       pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateEmailAuth(ctx context.Context, arg CreateEmailAuthParams) error {
	_, err := q.db.Exec(ctx, createEmailAuth, arg.UserID, arg.Email, arg.PasswordHash)
	return err
}

const isEmailRegistered = `-- name: IsEmailRegistered :one
SELECT EXISTS (
  SELECT 1
  FROM auth_identities
  WHERE provider = 'email' AND provider_user_id = lower($1)
) AS exists
`

func (q *Queries) IsEmailRegistered(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailRegistered, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
