// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: logins.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO logins (user_id, identity_id, result, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
`

type RecordLoginAttemptParams struct {
	UserID     pgtype.UUID
	IdentityID pgtype.UUID
	Result     LoginResult
	Ip         pgtype.Text
	UserAgent  pgtype.Text
}

// user_id and identity_id are nullable: an attempt against an email with no
// account still gets logged (IP/UA/time only) for anomaly detection.
func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLoginAttempt,
		arg.UserID,
		arg.IdentityID,
		arg.Result,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
