// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: maintenance.sql

package postgres

import (
	"context"
)

const removeExpiredPasswordResets = `-- name: RemoveExpiredPasswordResets :exec

SELECT remove_expired_password_resets()
`

// Thin wrappers around the cleanup functions defined in
// db/migrations/004_revoke_triggers.up.sql. Nothing invokes those functions
// on its own — see cmd/cron and internal/services/maintenance_service.go,
// which run all of them on a schedule via an external cron/CronJob.
func (q *Queries) RemoveExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeExpiredPasswordResets)
	return err
}

const removeOldLoginLogs = `-- name: RemoveOldLoginLogs :exec
SELECT remove_old_login_logs()
`

func (q *Queries) RemoveOldLoginLogs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeOldLoginLogs)
	return err
}

const removeOldPasswordResets = `-- name: RemoveOldPasswordResets :exec
SELECT remove_old_password_resets()
`

func (q *Queries) RemoveOldPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeOldPasswordResets)
	return err
}

const removeUnverifiedMFAFactors = `-- name: RemoveUnverifiedMFAFactors :exec
SELECT remove_unverified_mfa_factors()
`

func (q *Queries) RemoveUnverifiedMFAFactors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, removeUnverifiedMFAFactors)
	return err
}

const revokeExpiredSessions = `-- name: RevokeExpiredSessions :exec
SELECT revoke_expired_sessions()
`

func (q *Queries) RevokeExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeExpiredSessions)
	return err
}

const revokeOldSessions = `-- name: RevokeOldSessions :exec
SELECT revoke_old_sessions()
`

func (q *Queries) RevokeOldSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeOldSessions)
	return err
}
