// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mfa.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMFARecoveryCode = `-- name: CreateMFARecoveryCode :exec
INSERT INTO mfa_recovery_codes (factor_id, code_hash)
VALUES ($1, $2)
`

type CreateMFARecoveryCodeParams struct {
	FactorID pgtype.UUID
	CodeHash string
}

func (q *Queries) CreateMFARecoveryCode(ctx context.Context, arg CreateMFARecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createMFARecoveryCode, arg.FactorID, arg.CodeHash)
	return err
}

const deleteMFARecoveryCodesByFactor = `-- name: DeleteMFARecoveryCodesByFactor :exec
DELETE FROM mfa_recovery_codes WHERE factor_id = $1
`

// Invalidates every existing recovery code for a factor — called when
// (re-)verifying enrollment, since fresh codes are issued each time and the
// previous batch (if any, from an earlier enrollment of the same factor
// row) must not remain valid alongside them.
func (q *Queries) DeleteMFARecoveryCodesByFactor(ctx context.Context, factorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMFARecoveryCodesByFactor, factorID)
	return err
}

const deleteOTPFactor = `-- name: DeleteOTPFactor :exec
DELETE FROM mfa_factors
WHERE user_id = $1 AND type = $2
`

type DeleteOTPFactorParams struct {
	UserID pgtype.UUID
	Type   MfaType
}

func (q *Queries) DeleteOTPFactor(ctx context.Context, arg DeleteOTPFactorParams) error {
	_, err := q.db.Exec(ctx, deleteOTPFactor, arg.UserID, arg.Type)
	return err
}

const deleteTOTPFactor = `-- name: DeleteTOTPFactor :exec
DELETE FROM mfa_factors
WHERE user_id = $1 AND type = 'totp'
`

// Used to disable MFA outright; cascades to mfa_recovery_codes. A fresh
// enrollment afterwards is a plain insert via UpsertPendingTOTPFactor, not
// a conflict, since the row is actually gone.
func (q *Queries) DeleteTOTPFactor(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTOTPFactor, userID)
	return err
}

const getOTPFactorByUserID = `-- name: GetOTPFactorByUserID :one
SELECT id, verified, enabled, failed_attempts
FROM mfa_factors
WHERE user_id = $1 AND type = $2
`

type GetOTPFactorByUserIDParams struct {
	UserID pgtype.UUID
	Type   MfaType
}

type GetOTPFactorByUserIDRow struct {
	ID             pgtype.UUID
	Verified       pgtype.Bool
	Enabled        pgtype.Bool
	FailedAttempts pgtype.Int4
}

func (q *Queries) GetOTPFactorByUserID(ctx context.Context, arg GetOTPFactorByUserIDParams) (GetOTPFactorByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getOTPFactorByUserID, arg.UserID, arg.Type)
	var i GetOTPFactorByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Verified,
		&i.Enabled,
		&i.FailedAttempts,
	)
	return i, err
}

const getTOTPFactorByUserID = `-- name: GetTOTPFactorByUserID :one
SELECT id, secret, verified, enabled, failed_attempts, last_used_step
FROM mfa_factors
WHERE user_id = $1 AND type = 'totp'
`

type GetTOTPFactorByUserIDRow struct {
	ID             pgtype.UUID
	Secret         pgtype.Text
	Verified       pgtype.Bool
	Enabled        pgtype.Bool
	FailedAttempts pgtype.Int4
	LastUsedStep   pgtype.Int8
}

func (q *Queries) GetTOTPFactorByUserID(ctx context.Context, userID pgtype.UUID) (GetTOTPFactorByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTOTPFactorByUserID, userID)
	var i GetTOTPFactorByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Secret,
		&i.Verified,
		&i.Enabled,
		&i.FailedAttempts,
		&i.LastUsedStep,
	)
	return i, err
}

const getUnusedMFARecoveryCode = `-- name: GetUnusedMFARecoveryCode :one
SELECT id
FROM mfa_recovery_codes
WHERE code_hash = $1 AND used_at IS NULL
`

func (q *Queries) GetUnusedMFARecoveryCode(ctx context.Context, codeHash string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUnusedMFARecoveryCode, codeHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserEmailByID = `-- name: GetUserEmailByID :one
SELECT email FROM users WHERE id = $1
`

func (q *Queries) GetUserEmailByID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmailByID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const incrementOTPFactorFailedAttempts = `-- name: IncrementOTPFactorFailedAttempts :exec
UPDATE mfa_factors
SET failed_attempts = failed_attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementOTPFactorFailedAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPFactorFailedAttempts, id)
	return err
}

const incrementTOTPFailedAttempts = `-- name: IncrementTOTPFailedAttempts :exec
UPDATE mfa_factors
SET failed_attempts = failed_attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementTOTPFailedAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementTOTPFailedAttempts, id)
	return err
}

const markMFARecoveryCodeUsed = `-- name: MarkMFARecoveryCodeUsed :exec
UPDATE mfa_recovery_codes
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkMFARecoveryCodeUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMFARecoveryCodeUsed, id)
	return err
}

const recordOTPFactorSuccess = `-- name: RecordOTPFactorSuccess :exec
UPDATE mfa_factors
SET last_used_at = now(), failed_attempts = 0
WHERE id = $1
`

func (q *Queries) RecordOTPFactorSuccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordOTPFactorSuccess, id)
	return err
}

const recordTOTPSuccess = `-- name: RecordTOTPSuccess :exec
UPDATE mfa_factors
SET last_used_at = now(), last_used_step = $1, failed_attempts = 0
WHERE id = $2
`

type RecordTOTPSuccessParams struct {
	Step pgtype.Int8
	ID   pgtype.UUID
}

// last_used_step is compared against the incoming code's time-step on every
// attempt to reject replay of an already-used code within its own validity
// window — TOTP's 30-second step alone doesn't prevent this.
func (q *Queries) RecordTOTPSuccess(ctx context.Context, arg RecordTOTPSuccessParams) error {
	_, err := q.db.Exec(ctx, recordTOTPSuccess, arg.Step, arg.ID)
	return err
}

const upsertPendingOTPFactor = `-- name: UpsertPendingOTPFactor :one

INSERT INTO mfa_factors (user_id, type, verified, enabled, failed_attempts, last_used_at)
VALUES ($1, $2, FALSE, FALSE, 0, NULL)
ON CONFLICT (user_id, type) DO UPDATE
  SET verified = FALSE,
      enabled = FALSE,
      failed_attempts = 0,
      last_used_at = NULL,
      created_at = now()
RETURNING id
`

type UpsertPendingOTPFactorParams struct {
	UserID pgtype.UUID
	Type   MfaType
}

// Generic email/SMS OTP-factor queries — see the file header comment.
// Starts (or restarts) email/SMS enrollment for the given type. No secret
// is stored — the one-time code itself lives only in Redis
// (internal/auth/mfa_otp_code.go), scoped to this enrollment attempt.
func (q *Queries) UpsertPendingOTPFactor(ctx context.Context, arg UpsertPendingOTPFactorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPendingOTPFactor, arg.UserID, arg.Type)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertPendingTOTPFactor = `-- name: UpsertPendingTOTPFactor :one

INSERT INTO mfa_factors (user_id, type, secret, verified, enabled, failed_attempts, last_used_at, last_used_step)
VALUES ($1, 'totp', $2, FALSE, FALSE, 0, NULL, NULL)
ON CONFLICT (user_id, type) DO UPDATE
  SET secret = excluded.secret,
      verified = FALSE,
      enabled = FALSE,
      failed_attempts = 0,
      last_used_at = NULL,
      last_used_step = NULL,
      created_at = now()
RETURNING id
`

type UpsertPendingTOTPFactorParams struct {
	UserID pgtype.UUID
	Secret pgtype.Text
}

// TOTP has its own dedicated queries below (an encrypted secret and a
// last_used_step anti-replay column with no equivalent for other factor
// types). Email and SMS factors, further down, share one generic set of
// OTP-factor queries instead — unlike TOTP they store no secret at all
// (verifying either just means "we sent a code to this user's registered
// email/phone and they read it back to us"), so their DB shape is
// identical to each other and parameterizing by type is the right level of
// abstraction rather than duplicating the same queries twice.
// Starts (or restarts, if a previous attempt was abandoned) TOTP
// enrollment. ON CONFLICT target matches the UNIQUE(user_id, type)
// constraint — trg_prevent_multiple_totp additionally enforces this at the
// database level regardless of what application code does.
func (q *Queries) UpsertPendingTOTPFactor(ctx context.Context, arg UpsertPendingTOTPFactorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPendingTOTPFactor, arg.UserID, arg.Secret)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const verifyOTPFactor = `-- name: VerifyOTPFactor :exec
UPDATE mfa_factors
SET verified = TRUE, enabled = TRUE
WHERE id = $1
`

func (q *Queries) VerifyOTPFactor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyOTPFactor, id)
	return err
}

const verifyTOTPFactor = `-- name: VerifyTOTPFactor :exec
UPDATE mfa_factors
SET verified = TRUE, enabled = TRUE
WHERE id = $1
`

// Confirms enrollment: the user has proven they can generate a valid code
// with the secret, so the factor becomes active.
func (q *Queries) VerifyTOTPFactor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyTOTPFactor, id)
	return err
}
