// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mfa.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMFARecoveryCode = `-- name: CreateMFARecoveryCode :exec
INSERT INTO mfa_recovery_codes (factor_id, code_hash)
VALUES ($1, $2)
`

type CreateMFARecoveryCodeParams struct {
	FactorID pgtype.UUID
	CodeHash string
}

func (q *Queries) CreateMFARecoveryCode(ctx context.Context, arg CreateMFARecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createMFARecoveryCode, arg.FactorID, arg.CodeHash)
	return err
}

const deleteMFARecoveryCodesByFactor = `-- name: DeleteMFARecoveryCodesByFactor :exec
DELETE FROM mfa_recovery_codes WHERE factor_id = $1
`

// Invalidates every existing recovery code for a factor — called when
// (re-)verifying enrollment, since fresh codes are issued each time and the
// previous batch (if any, from an earlier enrollment of the same factor
// row) must not remain valid alongside them.
func (q *Queries) DeleteMFARecoveryCodesByFactor(ctx context.Context, factorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMFARecoveryCodesByFactor, factorID)
	return err
}

const deleteTOTPFactor = `-- name: DeleteTOTPFactor :exec
DELETE FROM mfa_factors
WHERE user_id = $1 AND type = 'totp'
`

// Used to disable MFA outright; cascades to mfa_recovery_codes. A fresh
// enrollment afterwards is a plain insert via UpsertPendingTOTPFactor, not
// a conflict, since the row is actually gone.
func (q *Queries) DeleteTOTPFactor(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTOTPFactor, userID)
	return err
}

const getTOTPFactorByUserID = `-- name: GetTOTPFactorByUserID :one
SELECT id, secret, verified, enabled, failed_attempts, last_used_step
FROM mfa_factors
WHERE user_id = $1 AND type = 'totp'
`

type GetTOTPFactorByUserIDRow struct {
	ID             pgtype.UUID
	Secret         pgtype.Text
	Verified       pgtype.Bool
	Enabled        pgtype.Bool
	FailedAttempts pgtype.Int4
	LastUsedStep   pgtype.Int8
}

func (q *Queries) GetTOTPFactorByUserID(ctx context.Context, userID pgtype.UUID) (GetTOTPFactorByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTOTPFactorByUserID, userID)
	var i GetTOTPFactorByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Secret,
		&i.Verified,
		&i.Enabled,
		&i.FailedAttempts,
		&i.LastUsedStep,
	)
	return i, err
}

const getUnusedMFARecoveryCode = `-- name: GetUnusedMFARecoveryCode :one
SELECT id
FROM mfa_recovery_codes
WHERE code_hash = $1 AND used_at IS NULL
`

func (q *Queries) GetUnusedMFARecoveryCode(ctx context.Context, codeHash string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUnusedMFARecoveryCode, codeHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const incrementTOTPFailedAttempts = `-- name: IncrementTOTPFailedAttempts :exec
UPDATE mfa_factors
SET failed_attempts = failed_attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementTOTPFailedAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementTOTPFailedAttempts, id)
	return err
}

const markMFARecoveryCodeUsed = `-- name: MarkMFARecoveryCodeUsed :exec
UPDATE mfa_recovery_codes
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkMFARecoveryCodeUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMFARecoveryCodeUsed, id)
	return err
}

const recordTOTPSuccess = `-- name: RecordTOTPSuccess :exec
UPDATE mfa_factors
SET last_used_at = now(), last_used_step = $1, failed_attempts = 0
WHERE id = $2
`

type RecordTOTPSuccessParams struct {
	Step pgtype.Int8
	ID   pgtype.UUID
}

// last_used_step is compared against the incoming code's time-step on every
// attempt to reject replay of an already-used code within its own validity
// window — TOTP's 30-second step alone doesn't prevent this.
func (q *Queries) RecordTOTPSuccess(ctx context.Context, arg RecordTOTPSuccessParams) error {
	_, err := q.db.Exec(ctx, recordTOTPSuccess, arg.Step, arg.ID)
	return err
}

const upsertPendingTOTPFactor = `-- name: UpsertPendingTOTPFactor :one

INSERT INTO mfa_factors (user_id, type, secret, verified, enabled, failed_attempts, last_used_at, last_used_step)
VALUES ($1, 'totp', $2, FALSE, FALSE, 0, NULL, NULL)
ON CONFLICT (user_id, type) DO UPDATE
  SET secret = excluded.secret,
      verified = FALSE,
      enabled = FALSE,
      failed_attempts = 0,
      last_used_at = NULL,
      last_used_step = NULL,
      created_at = now()
RETURNING id
`

type UpsertPendingTOTPFactorParams struct {
	UserID pgtype.UUID
	Secret pgtype.Text
}

// Only the 'totp' factor type has a working code path (see README's "Not
// implemented" section for sms/email); every query here is scoped to it
// explicitly rather than assuming it's the only row type mfa_factors will
// ever hold.
// Starts (or restarts, if a previous attempt was abandoned) TOTP
// enrollment. ON CONFLICT target matches the UNIQUE(user_id, type)
// constraint — trg_prevent_multiple_totp additionally enforces this at the
// database level regardless of what application code does.
func (q *Queries) UpsertPendingTOTPFactor(ctx context.Context, arg UpsertPendingTOTPFactorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPendingTOTPFactor, arg.UserID, arg.Secret)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const verifyTOTPFactor = `-- name: VerifyTOTPFactor :exec
UPDATE mfa_factors
SET verified = TRUE, enabled = TRUE
WHERE id = $1
`

// Confirms enrollment: the user has proven they can generate a valid code
// with the secret, so the factor becomes active.
func (q *Queries) VerifyTOTPFactor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyTOTPFactor, id)
	return err
}
