// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditAction string

const (
	AuditActionUpdateUser    AuditAction = "update_user"
	AuditActionChangeRole    AuditAction = "change_role"
	AuditActionChangeStatus  AuditAction = "change_status"
	AuditActionPasswordReset AuditAction = "password_reset"
	AuditActionEmailChange   AuditAction = "email_change"
	AuditActionMfaChange     AuditAction = "mfa_change"
	AuditActionUserBan       AuditAction = "user_ban"
	AuditActionUserUnban     AuditAction = "user_unban"
	AuditActionUserDeleted   AuditAction = "user_deleted"
	AuditActionAdminNote     AuditAction = "admin_note"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction
	Valid       bool // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type LoginResult string

const (
	LoginResultSuccess     LoginResult = "success"
	LoginResultFailed      LoginResult = "failed"
	LoginResultLocked      LoginResult = "locked"
	LoginResultMfaRequired LoginResult = "mfa_required"
)

func (e *LoginResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoginResult(s)
	case string:
		*e = LoginResult(s)
	default:
		return fmt.Errorf("unsupported scan type for LoginResult: %T", src)
	}
	return nil
}

type NullLoginResult struct {
	LoginResult LoginResult
	Valid       bool // Valid is true if LoginResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoginResult) Scan(value interface{}) error {
	if value == nil {
		ns.LoginResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoginResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoginResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoginResult), nil
}

type MfaType string

const (
	MfaTypeTotp  MfaType = "totp"
	MfaTypeSms   MfaType = "sms"
	MfaTypeEmail MfaType = "email"
)

func (e *MfaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MfaType(s)
	case string:
		*e = MfaType(s)
	default:
		return fmt.Errorf("unsupported scan type for MfaType: %T", src)
	}
	return nil
}

type NullMfaType struct {
	MfaType MfaType
	Valid   bool // Valid is true if MfaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMfaType) Scan(value interface{}) error {
	if value == nil {
		ns.MfaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MfaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMfaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MfaType), nil
}

type ProviderName string

const (
	ProviderNameEmail  ProviderName = "email"
	ProviderNameGoogle ProviderName = "google"
	ProviderNameApple  ProviderName = "apple"
)

func (e *ProviderName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderName(s)
	case string:
		*e = ProviderName(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderName: %T", src)
	}
	return nil
}

type NullProviderName struct {
	ProviderName ProviderName
	Valid        bool // Valid is true if ProviderName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderName) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderName), nil
}

type ResetSource string

const (
	ResetSourceWeb    ResetSource = "web"
	ResetSourceMobile ResetSource = "mobile"
	ResetSourceAdmin  ResetSource = "admin"
)

func (e *ResetSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResetSource(s)
	case string:
		*e = ResetSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ResetSource: %T", src)
	}
	return nil
}

type NullResetSource struct {
	ResetSource ResetSource
	Valid       bool // Valid is true if ResetSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResetSource) Scan(value interface{}) error {
	if value == nil {
		ns.ResetSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResetSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResetSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResetSource), nil
}

type UserOrigin string

const (
	UserOriginEmail  UserOrigin = "email"
	UserOriginGoogle UserOrigin = "google"
	UserOriginApple  UserOrigin = "apple"
)

func (e *UserOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserOrigin(s)
	case string:
		*e = UserOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for UserOrigin: %T", src)
	}
	return nil
}

type NullUserOrigin struct {
	UserOrigin UserOrigin
	Valid      bool // Valid is true if UserOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.UserOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserOrigin), nil
}

type UserRole string

const (
	UserRoleUser      UserRole = "user"
	UserRoleModerator UserRole = "moderator"
	UserRoleAdmin     UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusOffline  UserStatus = "offline"
	UserStatusDisabled UserStatus = "disabled"
	UserStatusBanned   UserStatus = "banned"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID             uuid.UUID
	ActorID        uuid.NullUUID
	ActorUsername  sql.NullString
	ActorEmail     sql.NullString
	TargetUserID   uuid.NullUUID
	TargetUsername sql.NullString
	TargetEmail    sql.NullString
	Action         AuditAction
	Changes        pqtype.NullRawMessage
	Reason         sql.NullString
	Ip             sql.NullString
	UserAgent      sql.NullString
	CreatedAt      sql.NullTime
}

type AuthIdentity struct {
	ID             uuid.UUID
	UserID         uuid.NullUUID
	Provider       ProviderName
	ProviderUserID string
	PasswordHash   sql.NullString
	FailedAttempts sql.NullInt32
	LastFailedAt   sql.NullTime
	LockedAt       sql.NullTime
	LastLogin      sql.NullTime
	CreatedAt      sql.NullTime
}

type Login struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	IdentityID uuid.NullUUID
	Result     LoginResult
	Ip         sql.NullString
	UserAgent  sql.NullString
	DeviceID   sql.NullString
	Location   sql.NullString
	CreatedAt  sql.NullTime
}

type MfaFactor struct {
	ID                   uuid.UUID
	UserID               uuid.NullUUID
	AuthenticatorAppName sql.NullString
	Type                 MfaType
	Secret               sql.NullString
	Enabled              sql.NullBool
	Verified             sql.NullBool
	CreatedAt            sql.NullTime
	FailedAttempts       sql.NullInt32
	LastUsedAt           sql.NullTime
	Revoked              sql.NullBool
}

type PasswordReset struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	ResetToken  string
	CreatedAt   sql.NullTime
	ExpiresAt   time.Time
	UsedAt      sql.NullTime
	BackupCodes pqtype.NullRawMessage
	Source      ResetSource
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.NullUUID
	CreatedAt        sql.NullTime
	ExpiresAt        time.Time
	RefreshTokenHash sql.NullString
	RotatedAt        sql.NullTime
	Revoked          sql.NullBool
	RevokedAt        sql.NullTime
	Ip               sql.NullString
	UserAgent        sql.NullString
	Metadata         pqtype.NullRawMessage
}

type User struct {
	ID                 uuid.UUID
	Email              string
	Username           string
	ProfilePhotoUrl    sql.NullString
	DisplayName        sql.NullString
	CreatedAt          sql.NullTime
	Status             NullUserStatus
	Role               NullUserRole
	LastLogin          sql.NullTime
	LastPasswordChange sql.NullTime
	Origin             NullUserOrigin
	LastSeen           sql.NullTime
	DeletedAt          sql.NullTime
}
