// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: password_resets.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (
  user_id, reset_token, expires_at, source
) VALUES (
  $1, $2, $3, $4
)
RETURNING id
`

type CreatePasswordResetParams struct {
	UserID     pgtype.UUID
	ResetToken string
	ExpiresAt  pgtype.Timestamptz
	Source     ResetSource
}

// reset_token stores HashOpaqueToken(raw), never the raw token itself — same
// convention as sessions.refresh_token_hash.
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPasswordReset,
		arg.UserID,
		arg.ResetToken,
		arg.ExpiresAt,
		arg.Source,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getActivePasswordReset = `-- name: GetActivePasswordReset :one
SELECT id, user_id, expires_at
FROM password_resets
WHERE reset_token = $1
  AND used_at IS NULL
  AND expires_at > now()
`

type GetActivePasswordResetRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

// Looks up an unused, unexpired reset request by its token hash. A missing
// row must be treated identically whether the token never existed, already
// expired, or was already consumed — see services.ResetPassword.
func (q *Queries) GetActivePasswordReset(ctx context.Context, resetToken string) (GetActivePasswordResetRow, error) {
	row := q.db.QueryRow(ctx, getActivePasswordReset, resetToken)
	var i GetActivePasswordResetRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getLatestPasswordResetForUser = `-- name: GetLatestPasswordResetForUser :one
SELECT created_at
FROM password_resets
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Used to enforce a regeneration cooldown between requests, mirroring
// StartEmailVerification's cooldown. A missing row (no prior request) is a
// normal, expected outcome for the caller to handle, not an error.
func (q *Queries) GetLatestPasswordResetForUser(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestPasswordResetForUser, userID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}
