// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO sessions (
  id, user_id, expires_at, refresh_token_hash, ip, user_agent, metadata
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
RETURNING id, user_id, expires_at, revoked
`

type CreateRefreshSessionParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	RefreshTokenHash pgtype.Text
	Ip               pgtype.Text
	UserAgent        pgtype.Text
	Metadata         []byte
}

type CreateRefreshSessionRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	Revoked   pgtype.Bool
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (CreateRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.RefreshTokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	var i CreateRefreshSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getRefreshSession = `-- name: GetRefreshSession :one
SELECT id, user_id, expires_at, refresh_token_hash, revoked
FROM sessions
WHERE id = $1
`

type GetRefreshSessionRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	RefreshTokenHash pgtype.Text
	Revoked          pgtype.Bool
}

func (q *Queries) GetRefreshSession(ctx context.Context, id pgtype.UUID) (GetRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, getRefreshSession, id)
	var i GetRefreshSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RefreshTokenHash,
		&i.Revoked,
	)
	return i, err
}

const listActiveSessionIDs = `-- name: ListActiveSessionIDs :many
SELECT id
FROM sessions
WHERE user_id = $1 AND revoked = FALSE
`

// Used before a bulk revoke (e.g. after a password reset) to also clear
// each session's Redis entry — revoking here only updates Postgres, which
// the refresh-token flow checks, but an already-issued access JWT stays
// valid until Redis's own session:<id> key is removed too.
func (q *Queries) ListActiveSessionIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveSessionIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOtherUserSessions = `-- name: RevokeAllOtherUserSessions :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = now()
WHERE user_id = $1
  AND id != $2
  AND revoked = FALSE
`

type RevokeAllOtherUserSessionsParams struct {
	UserID           pgtype.UUID
	CurrentSessionID pgtype.UUID
}

// Like RevokeAllUserSessions but keeps one session (the caller's current
// one) alive — used after an authenticated change-password, where the
// point is "log out everywhere else", not "log the user out of the request
// they just made".
func (q *Queries) RevokeAllOtherUserSessions(ctx context.Context, arg RevokeAllOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllOtherUserSessions, arg.UserID, arg.CurrentSessionID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = now()
WHERE user_id = $1 AND revoked = FALSE
`

// Kills every active session for a user in one statement — used after a
// password reset, since that's a security-sensitive event where staying
// logged in everywhere is the wrong default. Pair with ListActiveSessionIDs
// + auth.DeleteSession per ID to also clear the Redis side.
func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = now()
WHERE id = $1 AND revoked = FALSE
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateRefreshSession = `-- name: RotateRefreshSession :one
UPDATE sessions
SET refresh_token_hash = $1,
    rotated_at = now(),
    expires_at = $2
WHERE id = $3
  AND revoked = FALSE
RETURNING id, user_id, expires_at
`

type RotateRefreshSessionParams struct {
	RefreshTokenHash pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	ID               pgtype.UUID
}

type RotateRefreshSessionRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (RotateRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, rotateRefreshSession, arg.RefreshTokenHash, arg.ExpiresAt, arg.ID)
	var i RotateRefreshSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}
