// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO sessions (
  id, user_id, expires_at, refresh_token_hash, ip, user_agent, metadata
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
RETURNING id, user_id, expires_at, revoked
`

type CreateRefreshSessionParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	RefreshTokenHash pgtype.Text
	Ip               pgtype.Text
	UserAgent        pgtype.Text
	Metadata         []byte
}

type CreateRefreshSessionRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	Revoked   pgtype.Bool
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (CreateRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.RefreshTokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	var i CreateRefreshSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getRefreshSession = `-- name: GetRefreshSession :one
SELECT id, user_id, expires_at, refresh_token_hash, revoked
FROM sessions
WHERE id = $1
`

type GetRefreshSessionRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	RefreshTokenHash pgtype.Text
	Revoked          pgtype.Bool
}

func (q *Queries) GetRefreshSession(ctx context.Context, id pgtype.UUID) (GetRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, getRefreshSession, id)
	var i GetRefreshSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RefreshTokenHash,
		&i.Revoked,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = now()
WHERE id = $1 AND revoked = FALSE
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateRefreshSession = `-- name: RotateRefreshSession :one
UPDATE sessions
SET refresh_token_hash = $1,
    rotated_at = now(),
    expires_at = $2
WHERE id = $3
  AND revoked = FALSE
RETURNING id, user_id, expires_at
`

type RotateRefreshSessionParams struct {
	RefreshTokenHash pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	ID               pgtype.UUID
}

type RotateRefreshSessionRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (RotateRefreshSessionRow, error) {
	row := q.db.QueryRow(ctx, rotateRefreshSession, arg.RefreshTokenHash, arg.ExpiresAt, arg.ID)
	var i RotateRefreshSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}
