// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sso.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSSOIdentity = `-- name: CreateSSOIdentity :one
INSERT INTO auth_identities (user_id, provider, provider_user_id, password_hash)
VALUES ($1, $2, $3, NULL)
RETURNING id
`

type CreateSSOIdentityParams struct {
	UserID         pgtype.UUID
	Provider       ProviderName
	ProviderUserID string
}

// password_hash is always NULL for a non-email provider — enforced by the
// CHECK constraint on auth_identities regardless, but explicit here too.
func (q *Queries) CreateSSOIdentity(ctx context.Context, arg CreateSSOIdentityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSSOIdentity, arg.UserID, arg.Provider, arg.ProviderUserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSSOUser = `-- name: CreateSSOUser :one
INSERT INTO users (email, username, username_display, role, origin)
VALUES (
  lower($1),
  lower($2),
  $2,
  'user',
  $3
)
RETURNING id, username, username_display, role
`

type CreateSSOUserParams struct {
	Email           string
	UsernameDisplay string
	Origin          NullUserOrigin
}

type CreateSSOUserRow struct {
	ID              pgtype.UUID
	Username        string
	UsernameDisplay string
	Role            UserRole
}

func (q *Queries) CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (CreateSSOUserRow, error) {
	row := q.db.QueryRow(ctx, createSSOUser, arg.Email, arg.UsernameDisplay, arg.Origin)
	var i CreateSSOUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameDisplay,
		&i.Role,
	)
	return i, err
}

const getIdentityByProvider = `-- name: GetIdentityByProvider :one
SELECT
  u.id AS user_id,
  u.username,
  u.username_display,
  u.role,
  u.status,
  u.deleted_at,
  ai.id AS identity_id
FROM auth_identities ai
JOIN users u ON u.id = ai.user_id
WHERE ai.provider = $1 AND ai.provider_user_id = $2
`

type GetIdentityByProviderParams struct {
	Provider       ProviderName
	ProviderUserID string
}

type GetIdentityByProviderRow struct {
	UserID          pgtype.UUID
	Username        string
	UsernameDisplay string
	Role            UserRole
	Status          NullUserStatus
	DeletedAt       pgtype.Timestamptz
	IdentityID      pgtype.UUID
}

// Looks up an existing SSO login by (provider, provider_user_id) — the pair
// that's actually stable and unique per external account, unlike email
// (which a provider account could theoretically change).
func (q *Queries) GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (GetIdentityByProviderRow, error) {
	row := q.db.QueryRow(ctx, getIdentityByProvider, arg.Provider, arg.ProviderUserID)
	var i GetIdentityByProviderRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameDisplay,
		&i.Role,
		&i.Status,
		&i.DeletedAt,
		&i.IdentityID,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM users WHERE lower(email) = lower($1)
`

// Used only to detect a conflict (an account with this email already
// exists under some other identity) — see services.SSOLogin's comment on
// why that's treated as a conflict rather than auto-linked.
func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
