// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEmailAuth = `-- name: CreateEmailAuth :exec
INSERT INTO auth_identities (user_id, provider, provider_user_id, password_hash)
VALUES ($1, 'email', $2, $3)
`

type CreateEmailAuthParams struct {
	UserID         uuid.NullUUID
	ProviderUserID string
	PasswordHash   sql.NullString
}

func (q *Queries) CreateEmailAuth(ctx context.Context, arg CreateEmailAuthParams) error {
	_, err := q.db.ExecContext(ctx, createEmailAuth, arg.UserID, arg.ProviderUserID, arg.PasswordHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, role, origin)
VALUES ($1, $2, 'user', 'email')
RETURNING id, username
`

type CreateUserParams struct {
	Email    string
	Username string
}

type CreateUserRow struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Username)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}
