// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, username_display, role, origin)
VALUES (
  lower($1),                    -- normalize email
  lower($2),         -- canonical username (lowercased)
  $2,                -- case-preserving display
  'user',
  'email'
)
RETURNING id, email, username, username_display, role
`

type CreateUserParams struct {
	Email           string
	UsernameDisplay string
}

type CreateUserRow struct {
	ID              pgtype.UUID
	Email           string
	Username        string
	UsernameDisplay string
	Role            UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.UsernameDisplay)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.UsernameDisplay,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, username_display, role, status, deleted_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              pgtype.UUID
	Username        string
	UsernameDisplay string
	Role            UserRole
	Status          NullUserStatus
	DeletedAt       pgtype.Timestamptz
}

// Used by the refresh-token flow to re-derive current username/role/status
// for the new access token, rather than trusting the (possibly stale,
// already-expired) claims of the token being refreshed.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameDisplay,
		&i.Role,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE users
SET last_login = now(), last_seen = now()
WHERE id = $1
`

func (q *Queries) TouchUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, id)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE username = lower($1)
) AS exists
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
