// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webauthn.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWebAuthnCredentialsByUserID = `-- name: CountWebAuthnCredentialsByUserID :one
SELECT count(*) FROM webauthn_credentials WHERE user_id = $1
`

func (q *Queries) CountWebAuthnCredentialsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebAuthnCredentialsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one

INSERT INTO webauthn_credentials (user_id, credential_id, name, credential)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateWebAuthnCredentialParams struct {
	UserID       pgtype.UUID
	CredentialID []byte
	Name         pgtype.Text
	Credential   []byte
}

// Passkey/WebAuthn credential queries — see
// db/migrations/006_webauthn_credentials.up.sql for the storage-shape
// rationale (the credential itself is stored as opaque JSON; only
// credential_id is broken out as its own column, since it's the
// login-time lookup key).
func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.Name,
		arg.Credential,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials
WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Scoped to (id, user_id) together, not just id — a user must never be
// able to delete another user's passkey by guessing/enumerating its row id.
func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	return err
}

const getUserForWebAuthnLogin = `-- name: GetUserForWebAuthnLogin :one
SELECT id, username, role, status, deleted_at
FROM users
WHERE id = $1
`

type GetUserForWebAuthnLoginRow struct {
	ID        pgtype.UUID
	Username  string
	Role      UserRole
	Status    NullUserStatus
	DeletedAt pgtype.Timestamptz
}

// Used only inside the DiscoverableUserHandler callback during a passkey
// login: the assertion's user handle identifies the account before
// anything else about the request is known, so this intentionally isn't
// scoped to a specific auth provider (unlike GetEmailAuthByUserID) — a
// passkey can belong to an SSO-only account with no 'email' identity row.
func (q *Queries) GetUserForWebAuthnLogin(ctx context.Context, id pgtype.UUID) (GetUserForWebAuthnLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForWebAuthnLogin, id)
	var i GetUserForWebAuthnLoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const getWebAuthnCredentialsByUserID = `-- name: GetWebAuthnCredentialsByUserID :many
SELECT id, credential_id, name, credential, created_at, last_used_at
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at ASC
`

type GetWebAuthnCredentialsByUserIDRow struct {
	ID           pgtype.UUID
	CredentialID []byte
	Name         pgtype.Text
	Credential   []byte
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
}

// Used both to build the webauthn.User adapter (registration exclude-list,
// and login's DiscoverableUserHandler, which matches an assertion's rawID
// against exactly this list) and for the user-facing "your passkeys" view.
func (q *Queries) GetWebAuthnCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetWebAuthnCredentialsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWebAuthnCredentialsByUserIDRow
	for rows.Next() {
		var i GetWebAuthnCredentialsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.Name,
			&i.Credential,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWebAuthnCredential = `-- name: RenameWebAuthnCredential :exec
UPDATE webauthn_credentials
SET name = $1
WHERE id = $2 AND user_id = $3
`

type RenameWebAuthnCredentialParams struct {
	Name   pgtype.Text
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RenameWebAuthnCredential(ctx context.Context, arg RenameWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, renameWebAuthnCredential, arg.Name, arg.ID, arg.UserID)
	return err
}

const updateWebAuthnCredential = `-- name: UpdateWebAuthnCredential :exec
UPDATE webauthn_credentials
SET credential = $1, last_used_at = now()
WHERE id = $2
`

type UpdateWebAuthnCredentialParams struct {
	Credential []byte
	ID         pgtype.UUID
}

// Overwrites the stored credential wholesale with the value
// FinishLogin/FinishPasskeyLogin returns after a successful login — this
// is how the authenticator's sign-count (clone detection) and backup-state
// flags stay current. See the migration's comment for why a partial,
// column-level update isn't used instead.
func (q *Queries) UpdateWebAuthnCredential(ctx context.Context, arg UpdateWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredential, arg.Credential, arg.ID)
	return err
}
